### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by ScienceZone** [jjm2473/userjs-kuwo_lrc_downloader#1]
看不懂这种语言，能不能告诉一下酷我音乐歌词是怎么加密的吗？通过抓包得到的歌词下载后发现乱码，不知怎么解密。谢谢！

**Comment by jjm2473** [comment]
朋友,刚刚测试过,并没有加密啊.
这个js脚本是直接解析页面内容的,不是通过抓包.
可能流量包是有加密,没研究.

在谷歌浏览器安装Tampermonkey,再安装这个脚本试试.
具体的使用方法参考网上Tampermonkey教程.

**Comment by jjm2473** [comment]
浏览器脚本,非其他客户端使用
